template_one_demo:
  outputs:

    sqlserver:
      type: sqlserver
      driver: 'ODBC Driver 17 for SQL Server'
      server: localhost
      port: 1433
      database: TemplateOneSql
      schema: Template_one_schema_sql
      trusted_connection: True
      trust_cert: True


    snowflake:
      type: snowflake
      account:
      user:
      password:
      role:
      database:
      warehouse:
      schema: "devkit_connector"

  target: sqlserver
